name: flutter_notes_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'
# dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
